apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: uhyitoidl-python 
  janus-idp.io/tekton: uhyitoidl-python
  backstage.io/kubernetes-id: uhyitoidl-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: uhyitoidl-python
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml